{{- if .Values.gateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{- include "apigw-mocks.fullname" . | nindent 4 }}
spec:
  host: {{ include "apigw-mocks.fullname" . }}
  trafficPolicy:
    tls:
      mode: DISABLE
{{- end }}