{{- if .Values.gateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name:  {{- include "apigw-mocks.fullname" . | nindent 4 }}
spec:
  selector:
    {{- include "apigw-mocks.selectorLabels" . | nindent 4 }}
  servers:
  - port:
      number: {{ .Values.gateway.port }}
      name: http-prom
      protocol: HTTP
    {{- range .Values.gateway.hosts }}
    hosts:
    - {{ .host | quote }}
    {{- end }}
{{- end }}